name: vehicle_service_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_local_notifications: ^17.2.2
  dio: ^5.7.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true