// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrJNToRIy035WcqhcF6Azr0Lg51D07a_c',
    appId: '1:1066991300498:web:54e4024a50f4e22dd99b4b',
    messagingSenderId: '1066991300498',
    projectId: 'vehicle-service-app-f9627',
    authDomain: 'vehicle-service-app-f9627.firebaseapp.com',
    storageBucket: 'vehicle-service-app-f9627.firebasestorage.app',
    measurementId: 'G-W9XTD9PBC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX06FCs08X2VxEijIDC8CEu8pVC82bo5c',
    appId: '1:1066991300498:android:ee64b51636e421a2d99b4b',
    messagingSenderId: '1066991300498',
    projectId: 'vehicle-service-app-f9627',
    storageBucket: 'vehicle-service-app-f9627.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLxKOhalDaIddZZGCzFJte_xOQxz9HVD8',
    appId: '1:1066991300498:ios:22ac5c9502fdbd74d99b4b',
    messagingSenderId: '1066991300498',
    projectId: 'vehicle-service-app-f9627',
    storageBucket: 'vehicle-service-app-f9627.firebasestorage.app',
    iosBundleId: 'com.example.vehicleServiceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLxKOhalDaIddZZGCzFJte_xOQxz9HVD8',
    appId: '1:1066991300498:ios:22ac5c9502fdbd74d99b4b',
    messagingSenderId: '1066991300498',
    projectId: 'vehicle-service-app-f9627',
    storageBucket: 'vehicle-service-app-f9627.firebasestorage.app',
    iosBundleId: 'com.example.vehicleServiceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrJNToRIy035WcqhcF6Azr0Lg51D07a_c',
    appId: '1:1066991300498:web:70185738fdf4642ed99b4b',
    messagingSenderId: '1066991300498',
    projectId: 'vehicle-service-app-f9627',
    authDomain: 'vehicle-service-app-f9627.firebaseapp.com',
    storageBucket: 'vehicle-service-app-f9627.firebasestorage.app',
    measurementId: 'G-X40W0RFRGC',
  );
}
